//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFormatTests.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PFormatTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   2022/1/1
        ///
        ///2023/02/02 0:00:00
        ///
        ///20240303 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Expected1 {
            get {
                return ResourceManager.GetString("Expected1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2022/1/1
        ///
        ///2023/02/02 0:00:00
        ///
        ///20240303
        ///
        ///2022/1/1 2023/02/02 0:00:00 20240303 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Expected2 {
            get {
                return ResourceManager.GetString("Expected2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日時1	2022/1/1
        ///日時2	2023/2/2
        ///日時3	2024/3/3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Fields1 {
            get {
                return ResourceManager.GetString("Fields1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field 1	2022/1/1
        ///Field 2	2023/2/2
        ///Field 3	2024/3/3
        ///Field 4	${Field 1} ${{DateTime}Field 2} ${{DateTime}{yyyyMMdd}Field 3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Fields2 {
            get {
                return ResourceManager.GetString("Fields2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${日時1}
        ///
        ///${{DateTime}日時2}
        ///
        ///${{DateTime}{yyyyMMdd}日時3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${Field 1}
        ///
        ///${{DateTime}Field 2}
        ///
        ///${{DateTime}{yyyyMMdd}Field 3}
        ///
        ///${Field 4} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Input2 {
            get {
                return ResourceManager.GetString("Input2", resourceCulture);
            }
        }
    }
}
